ase
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name  'manual' }}
          name: Release ${{ github.ref_name || 'manual' }}
          body: |
            Multi-arch release built by CI
            - linux x86_64
            - linux aarch64
            - android arm64-v8a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dl/slipstream-linux-x86_64.tar.gz
            dl/slipstream-linux-aarch64.tar.gz
            dl/slipstream-android-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}